version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
      - .src/datasets:/home/datasets
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    networks:
      - hadoop_network
    
  jupyter:
    image: jupyter/pyspark-notebook
    container_name: pyspark_jupyter
    ports:
      - 8888:8888
      - 10000:10000
    environment:
      - JUPYTER_PASSWORD='password'
    volumes:
      - ./src/jupyter_notebooks/:/home/jovyan/jupyter_notebooks
    networks:
      - hadoop_network

  tictactoe:
    image: python:3.11.6
    container_name: tictactoe
    ports:
      - 8889:8889
      - 10001:10001
      - 10002:10002
      - 10003:10003
    volumes:
      - ./src/tictactoe/:/src/tictactoe/
    command: pip install hdfs
    command: tail -f /dev/null
    networks:
      - hadoop_network

  
  
volumes:
  hadoop_namenode:
  hadoop_datanode:

networks:
  hadoop_network:
